apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyspace.fullname" . }}-frontend
  labels:
    {{- include "hyspace.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "hyspace.frontendSelectorLabels" . | nindent 4 }}
