{{- if .Values.postgresql.internal }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hyspace.fullname" . }}-postgresql
  labels:
    {{- include "hyspace.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  serviceName: {{ include "hyspace.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hyspace
      app.kubernetes.io/instance: {{ include "hyspace.fullname" . }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hyspace
        app.kubernetes.io/instance: {{ include "hyspace.fullname" . }}
        app.kubernetes.io/component: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "hyspace.dbSecretName" . }}
                  key: {{ include "hyspace.dbSecretKey" . }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgresql.username }}"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgresql.username }}"]
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.postgresql.storage.storageClass }}
        storageClassName: {{ .Values.postgresql.storage.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.storage.size }}
{{- end }}
