{{- if not .Values.keycloak.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyspace.fullname" . }}-secret
  labels:
    {{- include "hyspace.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.postgresql.existingSecret }}
  postgresql-password: {{ .Values.postgresql.password | default (randAlphaNum 24) | quote }}
  {{- end }}
  {{- if .Values.keycloak.enabled }}
  {{ .Values.keycloak.existingSecretKeys.clientSecret }}: {{ .Values.keycloak.clientSecret | quote }}
  {{- end }}
{{- end }}
